# vi backend-service.yml

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chat-app
spec:
  selector:
    app: backend
  ports:
  - port: 5001
    targetPort: 5001

# kubectl apply -f backend-service.yml
# #  sudo -E kubectl port-forward service/backend 5001:5001 -n chat-app --address=0.0.0.0
