# vi ingress.yml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatapp-ingress
  namespace: chat-app
  labels:
    name: chatapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: chat-tws.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port: 
              number: 80
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: backend
            port: 
              number: 5001


# kubectl apply -f ingress.yml
# kubectl get ingress -n chat-app

# Create minikube ingress
# minikube addons enable ingress

# kubectl get ns
# kubectl get svc -n ingress-nginx

# lsof -i:80 (whatever is running on our machine on port no 80, we can get id)

# sudo -E kubectl port-forward svc/ingress-nginx-controller -n ingress-nginx 80:80
# kubectl delete -f frontend-service.yml
# kubectl apply -f frontend-service.yml

# kubectl delete -f .
# kubectl apply -f namespace.yml
# kubectl apply -f .

# sudo -E kubectl port-forward svc/ingress-nginx-controller -n ingress-nginx 80:80 --address=0.0.0.0


