# vi mongodb-pv.yml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: chat-app
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data


# kubectl apply -f mongodb-pv.yml
# kubectl get pv -n chat-app
